server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/inventorydb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
